config/routes.rb
Rails.application.routes.draw do
  resources :gears

end

app/models/gear.rb
class Gear < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  before_action :set_gear, only: [:show, :edit, :update, :destroy]

  # GET /gears
  # GET /gears.json
  def index
    @gears = Gear.all
  end

  # GET /gears/1
  # GET /gears/1.json
  def show
  end

  # GET /gears/new
  def new
    @gear = Gear.new
  end

  # GET /gears/1/edit
  def edit
  end

  # POST /gears
  # POST /gears.json
  def create
    @gear = Gear.new(gear_params)

    respond_to do |format|
      if @gear.save
        format.html { redirect_to @gear, notice: 'Gear was successfully created.' }
        format.json { render :show, status: :created, location: @gear }
      else
        format.html { render :new }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gears/1
  # PATCH/PUT /gears/1.json
  def update
    respond_to do |format|
      if @gear.update(gear_params)
        format.html { redirect_to @gear, notice: 'Gear was successfully updated.' }
        format.json { render :show, status: :ok, location: @gear }
      else
        format.html { render :edit }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gears/1
  # DELETE /gears/1.json
  def destroy
    @gear.destroy
    respond_to do |format|
      format.html { redirect_to gears_url, notice: 'Gear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gear
      @gear = Gear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gear_params
      params.require(:gear).permit(:type, :serial, :purchase_date, :price, :notes, :status, :manufacturer, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/views/gears/_form.html.erb
<%= form_for(@gear) do |f| %>
  <% if @gear.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gear.errors.count, "error") %> prohibited this gear from being saved:</h2>

      <ul>
      <% @gear.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :serial %><br>
    <%= f.text_field :serial %>
  </div>
  <div class="field">
    <%= f.label :purchase_date %><br>
    <%= f.datetime_select :purchase_date %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gears/edit.html.erb
<h1>Editing gear</h1>

<%= render 'form' %>

<%= link_to 'Show', @gear %> |
<%= link_to 'Back', gears_path %>

app/views/gears/index.html.erb
<h1>Listing gears</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Serial</th>
      <th>Purchase date</th>
      <th>Price</th>
      <th>Notes</th>
      <th>Status</th>
      <th>Manufacturer</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gears.each do |gear| %>
      <tr>
        <td><%= gear.type %></td>
        <td><%= gear.serial %></td>
        <td><%= gear.purchase_date %></td>
        <td><%= gear.price %></td>
        <td><%= gear.notes %></td>
        <td><%= gear.status %></td>
        <td><%= gear.manufacturer %></td>
        <td><%= gear.name %></td>
        <td><%= link_to 'Show', gear %></td>
        <td><%= link_to 'Edit', edit_gear_path(gear) %></td>
        <td><%= link_to 'Destroy', gear, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gear', new_gear_path %>

app/views/gears/new.html.erb
<h1>New gear</h1>

<%= render 'form' %>

<%= link_to 'Back', gears_path %>

app/views/gears/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @gear.type %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @gear.serial %>
</p>

<p>
  <strong>Purchase date:</strong>
  <%= @gear.purchase_date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @gear.price %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @gear.notes %>
</p>

<p>
  <strong>Status:</strong>
  <%= @gear.status %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @gear.manufacturer %>
</p>

<p>
  <strong>Name:</strong>
  <%= @gear.name %>
</p>

<%= link_to 'Edit', edit_gear_path(@gear) %> |
<%= link_to 'Back', gears_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gearstantial2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>